version: '3.6'
services:
    mysql:
        image: mysql:8.0.19
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: measurements
          MYSQL_USER: fadi
          MYSQL_PASSWORD: password
        ports:
          - "6604:3306"
