DROP TABLE IF EXISTS `MEASUREMENT`;
CREATE TABLE MEASUREMENT (
  `MEASUREMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEASUREMENT_VALUE` double NOT NULL,
  `MEASUREMENT_TIME` datetime NOT NULL,
  `MEASUREMENT_COMMENT` varchar(45) DEFAULT NULL,
  `station_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`MEASUREMENT_ID`)
)
